export type ContentSection={title:string;text:string;formula?:string};
export type Source={title:string;url:string};
export type VisualDocument={version:1;title:string;subtitle:string;sections:ContentSection[];sources:Source[];diagram:string;format:string;theme:string;photo?:string;points?:{x:number;y:number}[]};
export const EXAMPLES:Record<string,{prompt:string;sections:ContentSection[];diagram:string}>={
  'Cono y cilindro':{prompt:'Área y volumen del cono y cilindro',diagram:'solids',sections:[{title:'Cono',text:'r: radio · h: altura · g: generatriz. La altura es perpendicular a la base.',formula:'A_L=\\pi rg,\\quad A_T=\\pi r(g+r),\\quad V=\\frac{1}{3}\\pi r^2h'},{title:'Cilindro',text:'Dos bases circulares paralelas y una superficie lateral curva.',formula:'A_T=2\\pi r(h+r),\\quad V=\\pi r^2h'},{title:'Compara',text:'Si tienen igual radio y altura, el volumen del cono es un tercio del volumen del cilindro.'},{title:'Ejercicios',text:'Un cono tiene radio 4 cm, altura 6 cm y generatriz 7,2 cm. Calcula su área total y volumen.\nUn cilindro tiene radio 5 cm y altura 12 cm. Calcula su volumen.\nCompara un cono y un cilindro de radio 3 cm y altura 8 cm.'}]},
  'Seno y coseno':{prompt:'Modelando seno y coseno en la vida diaria',diagram:'wave',sections:[{title:'Modelo',text:'A es amplitud; B determina el período; C desplaza horizontalmente; D es la línea media.',formula:'f(x)=A\\sin(Bx+C)+D,\\quad T=\\frac{2\\pi}{|B|}'},{title:'Investiga',text:'Elige un fenómeno periódico: mareas, sonido, un péndulo o temperatura diaria.'},{title:'Representa',text:'Construye una tabla de valores, dibuja ejes e identifica máximo, mínimo y período.'},{title:'Explica',text:'Propón una función y describe qué representa cada parámetro. Explica las limitaciones del modelo.'}]},
  'Homotecia':{prompt:'Homotecia de un triángulo',diagram:'homothety',sections:[{title:'Transformación',text:'O es el centro y k es la razón. Los vértices correspondientes están alineados con O.',formula:'P^{\\prime}=O+k(P-O)'},{title:'Razón positiva',text:'La imagen queda en el mismo lado del centro. Si 0 < k < 1 se reduce; si k > 1 se amplía.'},{title:'Razón negativa',text:'La imagen queda al otro lado del centro. Su escala depende del valor absoluto de k.'},{title:'Practica',text:'Compara las proyecciones para k = −2, −0,5, 0,5 y 2. Identifica cuáles conservan o invierten el sentido respecto del centro.'}]},
  'Plano sala':{prompt:'Plano sala de música 5,87 x 8,55 m',diagram:'blueprint',sections:[{title:'Dimensiones',text:'Sala: 5,87 × 8,55 m. Tarima: 5,87 × 2,50 m.'},{title:'Alturas',text:'Muebles: 1,40 m. Estructura: 0,20 m. Piso de tarima: 1,60 m. Altura libre superior: 2,20 m.'},{title:'Escalera',text:'10 contrahuellas de 16 cm y 9 huellas de 30 cm; desarrollo aproximado: 2,70 m.'},{title:'Distribución',text:'40 puestos esquemáticos. Baranda de 1,00 m. Diagrama educativo; requiere revisión profesional para construcción.'}]},
  'Mol y masa molar':{prompt:'Mol, masa molecular y masa molar',diagram:'molecule',sections:[{title:'Mol',text:'Unidad de cantidad de sustancia. Un mol contiene exactamente el número de Avogadro de entidades.',formula:'N_A=6{,}02214076\\times10^{23}\\;\\mathrm{mol}^{-1}'},{title:'Masa molar',text:'Masa de un mol de sustancia, expresada habitualmente en g/mol.',formula:'n=\\frac{m}{M},\\quad m=nM'},{title:'Agua',text:'H₂O contiene dos átomos de hidrógeno y uno de oxígeno. Su masa molar aproximada es 18,02 g/mol.'},{title:'Practica',text:'Calcula cuántos moles hay en 36,04 g de agua. Determina la masa correspondiente a 0,5 mol de agua.'}]},
  'Folleto libre':{prompt:'Mi material educativo',diagram:'none',sections:[{title:'Idea principal',text:'Escribe aquí el contenido que quieres comunicar.'},{title:'Conceptos clave',text:'Organiza información breve y precisa. Puedes cambiar todos estos textos.'},{title:'Aplicación',text:'Agrega ejemplos, instrucciones o datos de tu tema.'},{title:'Actividad',text:'Describe qué deben hacer tus estudiantes o lectores.'}]}
};
export function draftFromPrompt(prompt:string):VisualDocument{
 const p=prompt.toLowerCase();const key=/cono|cilindro/.test(p)?'Cono y cilindro':/seno|coseno|onda/.test(p)?'Seno y coseno':/homotec/.test(p)?'Homotecia':/plano|sala|tarima/.test(p)?'Plano sala':/mol|química|quimica/.test(p)?'Mol y masa molar':'Folleto libre';const example=EXAMPLES[key];
 return{version:1,title:prompt.trim().slice(0,180)||example.prompt,subtitle:'Material educativo · Contenido editable',sections:structuredClone(example.sections),sources:[],diagram:example.diagram,format:'landscape',theme:example.diagram==='blueprint'?'blueprint':'educational'};
}
export function validateDocument(value:unknown):VisualDocument{
 const d=value as VisualDocument;if(!d||d.version!==1||typeof d.title!=='string'||!Array.isArray(d.sections)||d.sections.length>12)throw new Error('Documento inválido (máximo 12 secciones)');
 if(d.title.length>180||typeof d.subtitle!=='string'||d.subtitle.length>250)throw new Error('Título o subtítulo demasiado largo');
 if(!['solids','wave','homothety','blueprint','molecule','none'].includes(d.diagram)||!['landscape','portrait','square','brochure'].includes(d.format)||!['educational','editorial','blueprint'].includes(d.theme))throw new Error('Formato o diagrama inválido');
 for(const s of d.sections)if(typeof s.title!=='string'||s.title.length>100||typeof s.text!=='string'||s.text.length>1600||(s.formula!==undefined&&(typeof s.formula!=='string'||s.formula.length>500)))throw new Error('Sección inválida');
 if(!Array.isArray(d.sources)||d.sources.length>10||d.sources.some(s=>typeof s.title!=='string'||s.title.length>250||typeof s.url!=='string'||!/^https:\/\//.test(s.url)||s.url.length>1500))throw new Error('Fuente inválida');
 if(d.points&&(!Array.isArray(d.points)||d.points.length<2||d.points.length>2000||d.points.some(p=>!Number.isFinite(p.x)||!Number.isFinite(p.y))))throw new Error('Datos de gráfico inválidos');
 if(d.photo&&!/^data:image\/(png|jpeg|webp);base64,/.test(d.photo))throw new Error('Fotografía inválida');return structuredClone(d);
}
