import {cramerSections} from './cramer.js';
export const SECTION_DIAGRAMS=['water-cycle','solar-system','sun','mercury','venus','earth','mars','jupiter','saturn','uranus','neptune','solids','wave','homothety','blueprint','molecule','none','angle-central','angle-inscribed','angle-interior','angle-exterior','tangent'];
export type ContentKind='text'|'key-idea'|'formula'|'steps'|'exercise'|'warning'|'comparison'|'table';
export type ContentSection={title:string;text:string;formula?:string;kind?:ContentKind;sourceIds?:string[];visualHint?:string;priority?:number;visual?:{type:'flow'|'cycle';labels:string[]};equations?:string[];diagram?:string;table?:{headers:string[];rows:string[][]};image?:string;caption?:string;region?:'overview'|'worked-example'|'practice'|'footer';span?:1|2|3|4;icon?:'bulb'|'calculator'|'book'|'arrow'|'check'|'warning';tone?:'blue'|'pink'|'green'|'purple'|'gold'};
export type Source={id?:string;title:string;url:string};
export type Palette={primary:string;secondary:string;accent:string;background:string;surface:string;ink:string};
export type DesignSpec={preset:string;palette:Palette;background:'solid'|'soft-gradient'|'grid'|'dots'|'paper';density:'airy'|'medium'|'compact';columns?:1|2|3|4;cornerStyle?:'soft'|'rounded'|'square'};
export type VisualDocument={version:1|2;documentType?:'infographic'|'poster'|'worksheet'|'guide'|'brochure'|'technical-plan'|'activity';audience?:string;subject?:string;title:string;subtitle:string;sections:ContentSection[];sources:Source[];diagram:string;format:string;theme:string;design?:DesignSpec;aiMeta?:{provider?:string;model?:string;searchProvider?:string;researched?:boolean;generatedAt?:string};photo?:string;points?:{x:number;y:number}[]};

const DEFAULT_PALETTE:Palette={primary:'#12365f',secondary:'#2d73b9',accent:'#f0a43a',background:'#f4f9ff',surface:'#ffffff',ink:'#193658'};
export const DESIGN_PRESETS:Record<string,DesignSpec>={
 'educational-clean':{preset:'educational-clean',palette:DEFAULT_PALETTE,background:'soft-gradient',density:'medium',columns:2,cornerStyle:'rounded'},
 'mathematics-pastel':{preset:'mathematics-pastel',palette:{primary:'#153b78',secondary:'#3d8bd4',accent:'#ef9b2d',background:'#f7fbff',surface:'#ffffff',ink:'#183052'},background:'soft-gradient',density:'medium',columns:2,cornerStyle:'rounded'},
 'science-classroom':{preset:'science-classroom',palette:{primary:'#124b63',secondary:'#2b93a8',accent:'#62a96b',background:'#f2fbfb',surface:'#ffffff',ink:'#163a46'},background:'dots',density:'medium',columns:2,cornerStyle:'rounded'},
 'technical-blueprint':{preset:'technical-blueprint',palette:{primary:'#083c72',secondary:'#2374ad',accent:'#8bc6e8',background:'#062f5a',surface:'#0d477c',ink:'#e4f5ff'},background:'grid',density:'compact',columns:2,cornerStyle:'square'},
 'institutional':{preset:'institutional',palette:{primary:'#0c4b6e',secondary:'#167d85',accent:'#de9824',background:'#f6fafc',surface:'#ffffff',ink:'#17354a'},background:'solid',density:'compact',columns:2,cornerStyle:'soft'},
 'kids-illustrated':{preset:'kids-illustrated',palette:{primary:'#274f9e',secondary:'#58a8df',accent:'#f2b633',background:'#fffdf5',surface:'#ffffff',ink:'#17345e'},background:'dots',density:'airy',columns:2,cornerStyle:'rounded'},
 'minimal-editorial':{preset:'minimal-editorial',palette:{primary:'#2f3440',secondary:'#6f7a8b',accent:'#a57445',background:'#f4eee5',surface:'#fffdf9',ink:'#2d3038'},background:'paper',density:'airy',columns:2,cornerStyle:'soft'}
};

export const EXAMPLES:Record<string,{prompt:string;sections:ContentSection[];diagram:string}>={
 'Cono y cilindro':{prompt:'Área y volumen del cono y cilindro',diagram:'solids',sections:[{title:'Cono',kind:'formula',text:'r: radio · h: altura · g: generatriz. La altura es perpendicular a la base.',formula:'A_L=\\pi rg,\\quad A_T=\\pi r(g+r),\\quad V=\\frac{1}{3}\\pi r^2h'},{title:'Cilindro',kind:'formula',text:'Dos bases circulares paralelas y una superficie lateral curva.',formula:'A_T=2\\pi r(h+r),\\quad V=\\pi r^2h'},{title:'Compara',kind:'comparison',text:'Si tienen igual radio y altura, el volumen del cono es un tercio del volumen del cilindro.'},{title:'Ejercicios',kind:'exercise',text:'Un cono tiene radio 4 cm, altura 6 cm y generatriz 7,2 cm. Calcula su área total y volumen.\nUn cilindro tiene radio 5 cm y altura 12 cm. Calcula su volumen.\nCompara un cono y un cilindro de radio 3 cm y altura 8 cm.'}]},
 'Seno y coseno':{prompt:'Modelando seno y coseno en la vida diaria',diagram:'wave',sections:[{title:'Modelo',kind:'formula',text:'A es amplitud; B determina el período; C desplaza horizontalmente; D es la línea media.',formula:'f(x)=A\\sin(Bx+C)+D,\\quad T=\\frac{2\\pi}{|B|}'},{title:'Investiga',kind:'steps',text:'Elige un fenómeno periódico: mareas, sonido, un péndulo o temperatura diaria.'},{title:'Representa',kind:'steps',text:'Construye una tabla de valores, dibuja ejes e identifica máximo, mínimo y período.'},{title:'Explica',kind:'exercise',text:'Propón una función y describe qué representa cada parámetro. Explica las limitaciones del modelo.'}]},
 'Homotecia':{prompt:'Homotecia de un triángulo',diagram:'homothety',sections:[{title:'Transformación',kind:'key-idea',text:'O es el centro y k es la razón. Los vértices correspondientes están alineados con O.',formula:'P^{\\prime}=O+k(P-O)'},{title:'Razón positiva',text:'La imagen queda en el mismo lado del centro. Si 0 < k < 1 se reduce; si k > 1 se amplía.'},{title:'Razón negativa',text:'La imagen queda al otro lado del centro. Su escala depende del valor absoluto de k.'},{title:'Practica',kind:'exercise',text:'Compara las proyecciones para k = −2, −0,5, 0,5 y 2. Identifica cuáles conservan o invierten el sentido respecto del centro.'}]},
 'Plano sala':{prompt:'Plano sala de música 5,87 x 8,55 m',diagram:'blueprint',sections:[{title:'Dimensiones',text:'Sala: 5,87 × 8,55 m. Tarima: 5,87 × 2,50 m.'},{title:'Alturas',text:'Muebles: 1,40 m. Estructura: 0,20 m. Piso de tarima: 1,60 m. Altura libre superior: 2,20 m.'},{title:'Escalera',text:'10 contrahuellas de 16 cm y 9 huellas de 30 cm; desarrollo aproximado: 2,70 m.'},{title:'Distribución',kind:'warning',text:'40 puestos esquemáticos. Baranda de 1,00 m. Diagrama educativo; requiere revisión profesional para construcción.'}]},
 'Mol y masa molar':{prompt:'Mol, masa molecular y masa molar',diagram:'molecule',sections:[{title:'Mol',kind:'key-idea',text:'Unidad de cantidad de sustancia. Un mol contiene exactamente el número de Avogadro de entidades.',formula:'N_A=6{,}02214076\\times10^{23}\\;\\mathrm{mol}^{-1}'},{title:'Masa molar',kind:'formula',text:'Masa de un mol de sustancia, expresada habitualmente en g/mol.',formula:'n=\\frac{m}{M},\\quad m=nM'},{title:'Agua',text:'H₂O contiene dos átomos de hidrógeno y uno de oxígeno. Su masa molar aproximada es 18,02 g/mol.'},{title:'Practica',kind:'exercise',text:'Calcula cuántos moles hay en 36,04 g de agua. Determina la masa correspondiente a 0,5 mol de agua.'}]},
 'Folleto libre':{prompt:'Mi material educativo',diagram:'none',sections:[{title:'Idea principal',kind:'key-idea',text:'Escribe aquí el contenido que quieres comunicar.'},{title:'Conceptos clave',text:'Organiza información breve y precisa. Puedes cambiar todos estos textos.'},{title:'Aplicación',text:'Agrega ejemplos, instrucciones o datos de tu tema.'},{title:'Actividad',kind:'exercise',text:'Describe qué deben hacer tus estudiantes o lectores.'}]}
};
EXAMPLES['Circunferencias']={prompt:'Circunferencias: ángulos y fórmulas',diagram:'none',sections:[
 {title:'Ángulo central',text:'El vértice está en el centro. Su medida es igual a la del arco interceptado.',formula:'\\alpha=m(\\widehat{AB})',diagram:'angle-central',kind:'formula'},
 {title:'Ángulo inscrito',text:'El vértice está en la circunferencia. Mide la mitad del arco que intercepta.',formula:'\\alpha=\\frac{m(\\widehat{AB})}{2}',diagram:'angle-inscribed',kind:'formula'},
 {title:'Ángulo interior',text:'Dos cuerdas se cortan dentro. Suma los arcos interceptados por el ángulo y su opuesto.',formula:'\\alpha=\\frac{m(\\widehat{AB})+m(\\widehat{CD})}{2}',diagram:'angle-interior',kind:'formula'},
 {title:'Ángulo exterior',text:'Dos secantes se cortan fuera. Resta arco menor al mayor.',formula:'\\alpha=\\frac{m(\\widehat{AC})-m(\\widehat{BD})}{2}',diagram:'angle-exterior',kind:'formula'},
 {title:'Radio y tangente',text:'El radio que llega al punto de tangencia es perpendicular a la tangente.',formula:'OT\\perp t,\\quad \\alpha=90^\\circ',diagram:'tangent',kind:'formula'},
 {title:'Longitud de arco',text:'La fórmula usa el ángulo central en grados y el radio de la circunferencia.',formula:'L=\\frac{\\theta}{360^\\circ}\\,2\\pi r',kind:'formula'},
 {title:'Secantes',text:'Desde un punto exterior P: producto de segmento externo y secante completa.',formula:'PA\\cdot PB=PC\\cdot PD',kind:'formula'},
 {title:'Tangente y secante',text:'PT es tangente; PA es la parte externa y PB la secante completa.',formula:'PT^2=PA\\cdot PB',kind:'formula'}
]};
EXAMPLES['Método de Cramer']={prompt:'Método de Cramer con ejemplo resuelto 2x+y=5; x-y=1, horizontal estilo Canva y LaTeX',sections:cramerSections(''),diagram:'none'};

function presetForPrompt(p:string){if(/plano|arquitect|tarima|blueprint/.test(p))return 'technical-blueprint';if(/qu[ií]mica|mol|ciencia|biolog/.test(p))return 'science-classroom';if(/matem|cramer|homotec|seno|coseno|circun/.test(p))return 'mathematics-pastel';return 'educational-clean'}

export function draftFromPrompt(prompt:string):VisualDocument{
 const p=prompt.toLowerCase();const key=/circunferen/.test(p)?'Circunferencias':/cono|cilindro/.test(p)?'Cono y cilindro':/seno|coseno|onda/.test(p)?'Seno y coseno':/homotec/.test(p)?'Homotecia':/plano|sala|tarima/.test(p)?'Plano sala':/mol|química|quimica/.test(p)?'Mol y masa molar':'Folleto libre';const example=EXAMPLES[key];const preset=presetForPrompt(p);const design=structuredClone(DESIGN_PRESETS[preset]);if(key==='Circunferencias')design.columns=4;
 if(/cramer/.test(p)){return {version:2,documentType:/gu[ií]a/.test(p)?'worksheet':'infographic',title:'Método de Cramer',subtitle:'Resolución de sistemas de ecuaciones lineales · Paso a paso',sections:cramerSections(prompt),sources:[],diagram:'none',format:/vertical/.test(p)?'portrait':'landscape',theme:'educational',design};}
 return{version:2,documentType:/folleto/.test(p)?'brochure':/afiche|p[oó]ster/.test(p)?'poster':/plano/.test(p)?'technical-plan':/gu[ií]a/.test(p)?'worksheet':/actividad/.test(p)?'activity':'infographic',title:prompt.trim().slice(0,180)||example.prompt,subtitle:'Material educativo · Contenido editable',sections:structuredClone(example.sections),sources:[],diagram:example.diagram,format:'landscape',theme:design.preset==='technical-blueprint'?'blueprint':'educational',design};
}
const validColor=(v:unknown)=>typeof v==='string'&&/^#[0-9a-f]{6}$/i.test(v);
export function validateDocument(value:unknown):VisualDocument{
 const d=value as VisualDocument;if(!d||![1,2].includes(d.version)||typeof d.title!=='string'||!Array.isArray(d.sections)||d.sections.length>24)throw new Error('Documento inválido (máximo 24 secciones)');
 if(d.title.length>180||typeof d.subtitle!=='string'||d.subtitle.length>250)throw new Error('Título o subtítulo demasiado largo');
 if(!SECTION_DIAGRAMS.includes(d.diagram)||!['landscape','portrait','square','brochure'].includes(d.format)||!['educational','editorial','blueprint'].includes(d.theme))throw new Error('Formato o diagrama inválido');
 for(const s of d.sections)if(typeof s.title!=='string'||s.title.length>100||typeof s.text!=='string'||s.text.length>1600||(s.formula!==undefined&&(typeof s.formula!=='string'||s.formula.length>500))||(s.kind!==undefined&&!['text','key-idea','formula','steps','exercise','warning','comparison','table'].includes(s.kind)))throw new Error('Sección inválida');
 for(const s of d.sections){
  if(s.equations&&(!Array.isArray(s.equations)||s.equations.length>8||s.equations.some(t=>typeof t!=='string'||t.length>1200)))throw new Error('Ecuaciones inválidas');
  if(s.visual&&(!['flow','cycle'].includes(s.visual.type)||!Array.isArray(s.visual.labels)||s.visual.labels.length<2||s.visual.labels.length>6||s.visual.labels.some(v=>typeof v!=='string'||v.length>80)))throw new Error('Diagrama semántico inválido');
  if(s.diagram&&!SECTION_DIAGRAMS.includes(s.diagram))throw new Error('Diagrama de sección inválido');
  if(s.region&&!['overview','worked-example','practice','footer'].includes(s.region))throw new Error('Región inválida');
  if(s.span!==undefined&&![1,2,3,4].includes(s.span))throw new Error('Ancho de tarjeta inválido');
  if(s.icon&&!['bulb','calculator','book','arrow','check','warning'].includes(s.icon))throw new Error('Icono inválido');
  if(s.tone&&!['blue','pink','green','purple','gold'].includes(s.tone))throw new Error('Tono inválido');
  if(s.caption!==undefined&&(typeof s.caption!=='string'||s.caption.length>250))throw new Error('Pie de imagen inválido');
  if(s.image&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=\s]+$/.test(s.image))throw new Error('Imagen de sección inválida');
  if(s.table){const t=s.table;if(!Array.isArray(t.headers)||t.headers.length<1||t.headers.length>6||!Array.isArray(t.rows)||t.rows.length>20||t.rows.some(r=>!Array.isArray(r)||r.length!==t.headers.length)||[...t.headers,...t.rows.flat()].some(v=>typeof v!=='string'||v.length>250))throw new Error('Tabla inválida');}
 }
 if(d.documentType&&!['infographic','poster','worksheet','guide','brochure','technical-plan','activity'].includes(d.documentType))throw new Error('Tipo de documento inválido');
 if(!Array.isArray(d.sources)||d.sources.length>12||d.sources.some(s=>typeof s.title!=='string'||s.title.length>250||typeof s.url!=='string'||!/^https:\/\//.test(s.url)||s.url.length>1500))throw new Error('Fuente inválida');
 if(d.design){const x=d.design;if(typeof x.preset!=='string'||!['solid','soft-gradient','grid','dots','paper'].includes(x.background)||!['airy','medium','compact'].includes(x.density)||!x.palette||!['primary','secondary','accent','background','surface','ink'].every(k=>validColor(x.palette[k as keyof Palette])))throw new Error('Diseño inválido');if(x.cornerStyle&&!['soft','rounded','square'].includes(x.cornerStyle))throw new Error('Esquinas inválidas');if(x.columns!==undefined&&![1,2,3,4].includes(x.columns))throw new Error('Columnas inválidas');}
 if(d.points&&(!Array.isArray(d.points)||d.points.length<2||d.points.length>2000||d.points.some(p=>!Number.isFinite(p.x)||!Number.isFinite(p.y))))throw new Error('Datos de gráfico inválidos');
 if(d.photo&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=\s]+$/.test(d.photo))throw new Error('Fotografía inválida');return structuredClone(d);
}
