import test from 'node:test';import assert from 'node:assert/strict';
import handler from '../.test-dist/api/content-plan.js';
import {inferBrief} from '../dist/studio/intent.js';import {composeSVG} from '../dist/studio/composer.js';
const keys=['GEMINI_API_KEY','GOOGLE_API_KEY','GROQ_API_KEY','OPENROUTER_API_KEY','CEREBRAS_API_KEY','GEMINI_IMAGE_MODEL'];
async function isolated(fn){const env={...process.env},fetch=globalThis.fetch;for(const key of keys)delete process.env[key];try{await fn();}finally{globalThis.fetch=fetch;for(const key of keys)if(env[key]===undefined)delete process.env[key];else process.env[key]=env[key];}}
async function call(prompt){let result;const res={status(code){this.code=code;return this},setHeader(){},json(value){result={code:this.code,value}}};await handler({method:'POST',body:{prompt}},res);return result;}
test('prompt intent preserves orientation, type, school level and brief content',()=>{
 const b=inferBrief('Una infografía horizontal para 1 medio del sistema solar con información breve');assert.equal(b.format,'landscape');assert.equal(b.audience,'1 medio');assert.equal(b.topic,'Sistema solar');assert.equal(b.brief,true);
 assert.equal(inferBrief('afiche del ciclo del agua').format,'portrait');assert.equal(inferBrief('folleto horizontal de física').documentType,'brochure');
});
test('requested solar infographic is complete, attributed, horizontal and has planet illustrations',()=>isolated(async()=>{
 globalThis.fetch=()=>{throw Error('Built-in NASA baseline does not need unavailable providers')};const {code,value}=await call('Crea una infografía horizontal para 1 medio del sistema solar con información breve de cada astro');assert.equal(code,200);assert.equal(value.document.audience,'1 medio');assert.equal(value.document.format,'landscape');assert.equal(value.document.sections.length,10);assert.ok(value.pipeline.skills.includes('physics-model-router'));assert.equal(value.document.sources.length,2);
 const out=composeSVG(value.document);assert.ok(out.width>out.height);for(const name of ['Sol','Mercurio','Venus','Tierra','Marte','Júpiter','Saturno','Urano','Neptuno'])assert.ok(out.svg.includes(name));assert.ok(out.svg.includes('planet-saturn'));assert.ok(!out.svg.includes('Cono'));assert.ok(!out.svg.includes('contenido editable'));
}));
test('unconfigured generic topics fail explicitly without producing another topic or placeholder',()=>isolated(async()=>{
 const {code,value}=await call('afiche vertical sobre la fotosíntesis');assert.equal(code,503);assert.ok(!value.document);assert.match(value.error,/proveedor/);assert.equal((await call(42)).code,400);assert.equal((await call('x'.repeat(4001))).code,400);
 const custom=await call('Sistema solar, compara distancias y masas');assert.equal(custom.code,503);
}));
test('agents share prompt, extracted topic, pinned skills and research; critic triggers a targeted repair',()=>isolated(async()=>{
 process.env.GROQ_API_KEY='test-key';let calls=[],searches=[];const replies=[{topic:'Ciclo del agua',audience:'7° básico',domain:'science',documentType:'poster',format:'landscape',required:['evaporación','condensación','precipitación'],preset:'science-classroom'},{title:'Conos',subtitle:'',diagram:'none',sections:[{title:'Cono',text:'Tema incorrecto'}]},{accepted:false,issues:['Tema incorrecto: se pidió ciclo del agua']},{title:'El ciclo del agua',subtitle:'Transformaciones del agua',diagram:'none',sections:[{title:'Evaporación',text:'El agua líquida pasa a vapor.'},{title:'Condensación',text:'El vapor se enfría y forma gotas.'},{title:'Precipitación',span:4,text:'El agua cae desde las nubes.'}]},{accepted:true,issues:[]}];
 globalThis.fetch=async(url,options)=>{if(String(url).includes('wikipedia')){searches.push(url);return{ok:true,json:async()=>({query:{pages:{1:{title:'Ciclo del agua',extract:'El agua se evapora, se condensa y precipita.',fullurl:'https://es.wikipedia.org/wiki/Ciclo_del_agua'}}}})}}const body=JSON.parse(options.body);calls.push(body);return{ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(replies.shift())}}]})};};
 const {code,value}=await call('Crea un afiche vertical para 7° básico del ciclo del agua');assert.equal(code,200);assert.equal(value.document.format,'portrait');assert.equal(value.document.documentType,'poster');assert.equal(value.document.title,'El ciclo del agua');assert.equal(calls.length,5);assert.ok(decodeURIComponent(searches[0]).includes('Ciclo del agua'));assert.ok(!decodeURIComponent(searches[0]).includes('afiche vertical'));assert.ok(calls[1].messages[0].content.includes('# poster-design'));assert.ok(calls[1].messages[1].content.includes('se condensa'));assert.ok(calls[3].messages[1].content.includes('Tema incorrecto'));assert.ok(value.pipeline.skills.includes('science-illustration'));
}));
test('repeated critic rejection never returns the unrelated document',()=>isolated(async()=>{
 process.env.GROQ_API_KEY='test-key';let i=0;globalThis.fetch=async(url)=>{if(String(url).includes('wikipedia'))return{ok:true,json:async()=>({})};const replies=[{topic:'Fotosíntesis'},{title:'Cramer',sections:[{title:'Sistema',text:'Ecuaciones'}],diagram:'none'},{accepted:false,issues:['Tema ajeno']},{title:'Cramer',sections:[{title:'Sistema',text:'Ecuaciones'}],diagram:'none'},{accepted:false,issues:['Tema ajeno']}];return{ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(replies[i++])}}]})};};const {code,value}=await call('Infografía de fotosíntesis');assert.equal(code,503);assert.ok(!value.document);
}));
test('semantic cycle diagrams retain exact labels and reject unbounded or active data',async()=>{
 const {validateDocument}=await import('../dist/studio/content.js');const {solarDocument}=await import('../dist/studio/solar.js');const d=solarDocument(inferBrief('infografía cuadrada del sistema solar'));d.diagram='none';d.sections=[{title:'Ciclo del agua',text:'Cambios de estado',visual:{type:'cycle',labels:['Evaporación','Condensación','Precipitación','Infiltración']}}];const out=composeSVG(d);assert.equal(out.width,out.height);assert.ok(out.svg.includes('semantic-arrow'));assert.ok(out.svg.includes('Condensación'));assert.throws(()=>validateDocument({...d,sections:[{title:'X',text:'',visual:{type:'raw-svg',labels:['a','b']}}]}));
});

test('the exact public Cramer example accepts sentence punctuation after an equation',()=>isolated(async()=>{
 const {code,value}=await call('Crea una infografía del método de Cramer con el ejemplo resuelto 2x+y=5; x-y=1. Incluye todos los pasos, comprobación y fórmulas LaTeX, estilo Canva pastel.');assert.equal(code,200);assert.ok(value.document.sections.some(s=>s.title==='Comprobación'));assert.ok(value.document.sections.some(s=>s.equations?.some(t=>t.startsWith('x=')&&t.endsWith('=2'))));
}));
test('Gemini agents keep keys in headers and reserve output tokens for complete structured responses',()=>isolated(async()=>{
 process.env.GEMINI_API_KEY=' private-test-key ';const calls=[];const replies=[{topic:'Ciclo del agua',domain:'science',preset:'science-classroom'},{title:'El ciclo del agua',sections:[{title:'Etapas',text:'El agua cambia de estado.',visual:{type:'cycle',labels:['Evaporación','Condensación','Precipitación']}}]},{accepted:true,issues:[]}];
 globalThis.fetch=async(url,opts)=>{const body=JSON.parse(opts.body);assert.ok(!String(url).includes('private-test-key'));assert.equal(opts.headers['x-goog-api-key'],'private-test-key');if(body.tools)return{ok:true,json:async()=>({candidates:[{content:{parts:[{text:'Evaporación, condensación y precipitación.'}]},groundingMetadata:{groundingChunks:[{web:{title:'Fuente educativa',uri:'https://example.org/agua'}}]}}]})};calls.push(body);return{ok:true,json:async()=>({candidates:[{content:{parts:[{text:JSON.stringify(replies.shift())}]}}]})};};
 const {code,value}=await call('Afiche vertical del ciclo del agua');assert.equal(code,200);assert.equal(value.document.aiMeta.provider,'Gemini');assert.equal(value.document.aiMeta.searchProvider,'Gemini Google Search');assert.deepEqual(calls.map(b=>b.generationConfig.maxOutputTokens),[1200,6000,1400]);assert.ok(calls.every(b=>b.generationConfig.thinkingConfig.thinkingBudget===0));assert.equal(value.document.sections[0].visual.type,'cycle');
}));
test('provider quota failures are actionable and never expose key values',()=>isolated(async()=>{
 process.env.GEMINI_API_KEY='private-test-key';globalThis.fetch=async()=>({ok:false,status:429});const {code,value}=await call('afiche de fotosíntesis');assert.equal(code,503);assert.match(value.error,/cuota/);assert.ok(!JSON.stringify(value).includes('private-test-key'));
}));

test('a requested central water-cycle illustration survives the editorial and validation agents',()=>isolated(async()=>{
 process.env.GROQ_API_KEY='test-key';const replies=[{topic:'Ciclo del agua',domain:'science',preset:'science-classroom'},{title:'Ciclo del agua',diagram:'none',sections:[{title:'Evaporación',span:4,text:'El calor convierte el agua en vapor.'},{title:'Condensación',span:4,text:'El vapor se enfría y forma gotas.'},{title:'Precipitación',span:4,text:'El agua cae como lluvia, nieve o granizo.'}]},{accepted:true,issues:[]}];
 globalThis.fetch=async(url)=>String(url).includes('wikipedia')?{ok:true,json:async()=>({})}:{ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(replies.shift())}}]})};
 const {code,value}=await call('Crea un afiche vertical del ciclo del agua con una ilustración central');assert.equal(code,200);assert.equal(value.document.diagram,'water-cycle');const out=composeSVG(value.document);assert.match(out.svg,/data-diagram="water-cycle"/);assert.match(out.svg,/Agua subterránea/);assert.match(out.svg,/water-arrow/);assert.ok(out.height>out.width);const placements=[...out.svg.matchAll(/data-section="\d+"[^>]*><title>[^<]*<\/title><rect x="(\d+)"/g)].map(m=>m[1]);assert.equal(new Set(placements).size,2);
}));
test('long grounding redirect URLs remain linked without expanding the image footer',async()=>{
 const {solarDocument}=await import('../dist/studio/solar.js');const d=solarDocument(inferBrief('afiche vertical del sistema solar'));d.sources=[{id:'s1',title:'NASA',url:'https://example.org/redirect/'+ 'x'.repeat(900)}];const long=composeSVG(d);const short=composeSVG({...d,sources:[{...d.sources[0],url:'https://example.org'}]});assert.equal(long.height,short.height);assert.match(long.svg,/\[1\] NASA/);assert.ok(long.svg.includes(d.sources[0].url));
});
