import "./style.css";
import{buildAdvancedSolarSystemScene,buildSingleBodyScene,buildPlasmaDemoScene,buildMoleculeObject,MOLECULES,buildCellObject,defaultAnimalCell,createScientificRenderer,applyRendererPostFX,createBloomPipeline}from"./index";
const canvas=document.querySelector("#view")as HTMLCanvasElement,status=document.querySelector("#status")!,backendEl=document.querySelector("#backend")!,fpsEl=document.querySelector("#fps")!,pcEl=document.querySelector("#particle-count")!,exposure=document.querySelector("#exposure")as HTMLInputElement,bloom=document.querySelector("#bloom")as HTMLInputElement,particles=document.querySelector("#particles")as HTMLInputElement;
let handle:any,camera:any,current:any,pipeline:any=null,last=performance.now(),frames=0,currentScene="solar";
async function init(){handle=await createScientificRenderer({canvas,antialias:true});backendEl.textContent=handle.backend.toUpperCase();status.textContent="Render listo · "+handle.backend.toUpperCase();const{THREE,renderer}=handle;camera=new THREE.PerspectiveCamera(48,1,.01,100);camera.position.set(0,5.8,8.6);camera.lookAt(2.5,0,0);applyRendererPostFX(renderer,THREE,{exposure:+exposure.value,bloom:+bloom.value});await loadScene("solar");resize();addEventListener("resize",resize);animate()}
function resize(){const w=canvas.clientWidth,h=canvas.clientHeight;handle.renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
async function wrappedObject(object:any){const THREE=handle.THREE,scene=new THREE.Scene();scene.background=new THREE.Color(0x01040a);scene.add(object);scene.add(new THREE.DirectionalLight(0xffffff,4));scene.add(new THREE.DirectionalLight(0x60a5fa,1.4));scene.add(new THREE.AmbientLight(0x334466,.8));return{scene,root:object}}
async function loadScene(name:string){
  currentScene=name;document.querySelectorAll("[data-scene]").forEach(b=>b.classList.toggle("active",(b as HTMLElement).dataset.scene===name));
  if(name==="solar"||name==="solar-date"){current=await buildAdvancedSolarSystemScene({particleCount:+particles.value,seed:42,layout:name==="solar-date"?"ephemeris":"educational",ephemerisDate:new Date()});camera.position.set(0,7.4,10.5);camera.lookAt(2.5,0,0)}
  else if(name==="sun"||name==="saturn"){current=await buildSingleBodyScene(name as"sun"|"saturn",{particleCount:+particles.value,seed:42});camera.position.set(0,.4,5.5);camera.lookAt(0,0,0)}
  else if(name==="h2o"){current=await wrappedObject(await buildMoleculeObject(MOLECULES.H2O,1));camera.position.set(0,0,5);camera.lookAt(0,0,0)}
  else if(name==="cell"){current=await wrappedObject(await buildCellObject(defaultAnimalCell()));camera.position.set(0,0,6.5);camera.lookAt(0,0,0)}
  else if(name==="plasma"){current=await buildPlasmaDemoScene({count:+particles.value,seed:42});camera.position.set(0,0,6);camera.lookAt(0,0,0)}
  pipeline=await createBloomPipeline(handle.renderer,current.scene,camera,{bloom:+bloom.value,bloomRadius:.38,bloomThreshold:.68});
  pcEl.textContent=current.corona?String(current.corona.system.config.count):current.plasma?String(current.plasma.system.config.count):"—";status.textContent="Render listo · "+handle.backend.toUpperCase()+(pipeline?" · bloom GPU":" · glow fallback");
}
function animate(t=performance.now()){requestAnimationFrame(animate);const dt=Math.min(.033,(t-last)/1000);frames++;if(t-last>1000){fpsEl.textContent=String(Math.round(frames*1000/(t-last)));frames=0;last=t}if(current?.root)current.root.rotation.y+=dt*.08;if(current?.mesh)current.mesh.rotation.y+=dt*.12;if(current?.corona){current.corona.system.step(dt);current.corona.geometry.attributes.position.needsUpdate=true;current.corona.points.rotation.y+=dt*.08}if(current?.plasma){current.plasma.system.step(dt);current.plasma.geometry.attributes.position.needsUpdate=true}if(pipeline?.render)pipeline.render();else handle.renderer.render(current.scene,camera)}
document.querySelectorAll("[data-scene]").forEach(btn=>btn.addEventListener("click",()=>loadScene((btn as HTMLElement).dataset.scene!)));exposure.addEventListener("input",()=>handle.renderer.toneMappingExposure=+exposure.value);bloom.addEventListener("change",()=>loadScene(currentScene));particles.addEventListener("change",()=>loadScene(currentScene));init().catch(e=>{status.textContent="Error: "+String(e);console.error(e)});
